### ISSUE TITLE
Synopsis Should Be Prepared

### ISSUE THREAD

**Issue by kinderasteroid** [kinderneutron/Documentation#1]

**Comment by kinderasteroid** [comment]
Keep Replying From Below On This

**Comment by kinderasteroid** [comment]
@kinderneutron/kinderneutron 

Guys Note that We Need Not Use Latex. Please Give The Brief How We Will Make The Synopsis

**Comment by viyoladsouz** [comment]
before doing synopsis we have to talk to ma'am rightt, that we want to continue on the same project.

**Comment by varshavshetty** [comment]
Yeah even I feel the same we shd speak with Maam before we proceed.

**Comment by kinderasteroid** [comment]
Yes @varshavshetty  and @viyoladsouz, We will Have a Discussion With Ma'am Tomorrow and We Can Start Working On Synopsis.
